export default {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    TOGGLE_MENU: 'TOGGLE_MENU',
    USER_DATA: 'USER_DATA',
    ROUTER_OBJECT: 'ROUTER_OBJECT',
    LOADING_STATUS: 'LOADING_STATUS',
    UPDATA_ROUTER: 'UPDATA_ROUTER',
    TAB_LIST: 'TAB_LIST',
    TAB_LIST_DEL: 'TAB_LIST_DEL',
    TAB_LIST_DEL_ALL: 'TAB_LIST_DEL_ALL',
    ROLE_LIST: 'ROLE_LIST',
    CLUB_FORM: 'CLUB_FORM',
    ADMIN_FLAG: 'ADMIN_FLAG'
};